services:
  traefik:
    image: traefik:v3
    restart: always
    container_name: traefik
    command:
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.file.filename=/etc/traefik/traefik_dynamic.yml'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=ferreirakevin325@gmail.com' # Substitua pelo seu email
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro' # conecta ao socket do docker e consegue visualizar os container
      - './traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml' # Monta o arquivo de configuração dinâmica
    networks:
      - traefik
    labels:
      - 'traefik.http.routers.traefik-dashboard.rule=Host(`traefik.app-demo.duckdns.org`)' # dominio que foi configurado no duck dns
      - 'traefik.http.routers.traefik-dashboard.service=api@internal'
      - 'traefik.http.routers.traefik-dashboard.entrypoints=websecure'
      - 'traefik.http.routers.traefik-dashboard.tls.certresolver=myresolver'
      # - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth@file" # Descomente para ativar autenticação

networks:
  traefik:
    external: true